In [2]:
import numpy as np

In [26]:
A = np.array([
        [2, 0, 0, 0],
        [3, 3, 0, 0],
        [4, 4, 4, 4],
        [0, 0, 5, 5]
    ], dtype=np.float64)

In [5]:
A[0]

array([2., 0., 0., 0.])

In [6]:
A[3,2]

np.float64(5.0)

In [27]:
class MatrixIsSingular(Exception): pass

def fixRowZero(A) :
    if A[0,0] == 0 :
        print(f"first if {A}")
        A[0] = A[0] + A[1]
        print(f"Operation A[0]+[A1] performed {A[0]}")
        print("*"*20)
        
    if A[0,0] == 0 :
        A[0] = A[0] + A[2]
    if A[0,0] == 0 :
        A[0] = A[0] + A[3]
    if A[0,0] == 0 :
        raise MatrixIsSingular()
    
    print("*"*10)
    print(A[0])
    A[0] = A[0] / A[0,0]
    print("*"*10)
    print(A[0])
    
    print(A)
    return A

def fixRowOne(A) :
    A[1] = A[1] - A[1,0] * A[0]
    if A[1,1] == 0 :
        A[1] = A[1] + A[2]
        A[1] = A[1] - A[1,0] * A[0]
    if A[1,1] == 0 :
        A[1] = A[1] + A[3]
        A[1] = A[1] - A[1,0] * A[0]
    if A[1,1] == 0 :
        raise MatrixIsSingular()
    A[1] = A[1] / A[1,1]
    return A


In [28]:
fixRowZero(A)


**********
[2. 0. 0. 0.]
**********
[1. 0. 0. 0.]
[[1. 0. 0. 0.]
 [3. 3. 0. 0.]
 [4. 4. 4. 4.]
 [0. 0. 5. 5.]]


array([[1., 0., 0., 0.],
       [3., 3., 0., 0.],
       [4., 4., 4., 4.],
       [0., 0., 5., 5.]])

In [30]:
print(A)
print("="*10)
fixRowOne(A)

[[1. 0. 0. 0.]
 [3. 3. 0. 0.]
 [4. 4. 4. 4.]
 [0. 0. 5. 5.]]


array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [4., 4., 4., 4.],
       [0., 0., 5., 5.]])

In [29]:
def fixRowTwo(A) :
    # Insert code below to set the sub-diagonal elements of row two to zero (there are two of them).
    A[2] = A[2] - A[2,0] * A[0]
    A[2] = A[2] - A[2,1] * A[1]
    
    # Next we'll test that the diagonal element is not zero.
    if A[2,2] == 0 :
        A[2] = A[2] + A[3]
        A[2] = A[2] - A[2,0] * A[0]
        A[2] = A[2] - A[2,1] * A[1]
        
        
    if A[2,2] == 0 :
        raise MatrixIsSingular()
    # Finally set the diagonal element to one by dividing the whole row by that element.
    
    A[2] = A[2]/A[2,2]
    
    return A

In [31]:
fixRowTwo(A)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 1.],
       [0., 0., 5., 5.]])

In [ ]:
def fixRowThree(A) :
    # Insert code below to set the sub-diagonal elements of row three to zero.
    A[3] = A[3] - A[3,0] * A[0]
    A[3] = A[3] - A[3,1] * A[1]
    A[3] = A[3] - A[3,2] * A[2]
    
    
    # Complete the if statement to test if the diagonal element is zero.
    if A[3,3] == 0:
        raise MatrixIsSingular()
    # Transform the row to set the diagonal element to one.
    
    A[3] = A[3]/A[3,3]
    
    return A

In [34]:
A[3,3]

np.float64(0.0)

In [37]:
def isSingular(A) :
    B = np.array(A, dtype=np.float64) # Make B as a copy of A, since we're going to alter it's values.
    try:
        fixRowZero(B)
        fixRowOne(B)
        fixRowTwo(B)
        fixRowThree(B)
    except MatrixIsSingular:
        return True
    return False

A = np.array([
        [2, 0, 0, 0],
        [0, 3, 0, 0],
        [0, 0, 4, 4],
        [0, 0, 5, 5]
    ], dtype=np.float64)
isSingular(A)

**********
[2. 0. 0. 0.]
**********
[1. 0. 0. 0.]
[[1. 0. 0. 0.]
 [0. 3. 0. 0.]
 [0. 0. 4. 4.]
 [0. 0. 5. 5.]]


True

In [38]:
A = np.array([
        [0, 7, -5, 3],
        [2, 8, 0, 4],
        [3, 12, 0, 5],
        [1, 3, 1, 3]
    ], dtype=np.float64)
fixRowZero(A)

first if [[ 0.  7. -5.  3.]
 [ 2.  8.  0.  4.]
 [ 3. 12.  0.  5.]
 [ 1.  3.  1.  3.]]
Operation A[0]+[A1] performed [ 2. 15. -5.  7.]
********************
**********
[ 2. 15. -5.  7.]
**********
[ 1.   7.5 -2.5  3.5]
[[ 1.   7.5 -2.5  3.5]
 [ 2.   8.   0.   4. ]
 [ 3.  12.   0.   5. ]
 [ 1.   3.   1.   3. ]]


array([[ 1. ,  7.5, -2.5,  3.5],
       [ 2. ,  8. ,  0. ,  4. ],
       [ 3. , 12. ,  0. ,  5. ],
       [ 1. ,  3. ,  1. ,  3. ]])

In [39]:
fixRowOne(A)

array([[ 1.        ,  7.5       , -2.5       ,  3.5       ],
       [-0.        ,  1.        , -0.71428571,  0.42857143],
       [ 3.        , 12.        ,  0.        ,  5.        ],
       [ 1.        ,  3.        ,  1.        ,  3.        ]])

In [40]:
fixRowTwo(A)

array([[ 1.        ,  7.5       , -2.5       ,  3.5       ],
       [-0.        ,  1.        , -0.71428571,  0.42857143],
       [ 0.        ,  0.        ,  1.        ,  1.5       ],
       [ 1.        ,  3.        ,  1.        ,  3.        ]])

In [41]:
fixRowThree(A)

array([[ 1.        ,  7.5       , -2.5       ,  3.5       ],
       [-0.        ,  1.        , -0.71428571,  0.42857143],
       [ 0.        ,  0.        ,  1.        ,  1.5       ],
       [ 0.        ,  0.        ,  0.        ,  1.        ]])